# Generated by Django 2.0.5 on 2018-05-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth', models.DecimalField(decimal_places=10, max_digits=30)),
                ('btc', models.DecimalField(decimal_places=10, max_digits=30)),
            ],
        ),
    ]
