# Generated by Django 2.0.5 on 2018-05-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='private_key',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='public_key',
            field=models.TextField(null=True),
        ),
    ]
