# Generated by Django 2.0.5 on 2018-05-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='main_balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='balance',
            new_name='main_balance',
        ),
    ]
