# Generated by Django 2.0.5 on 2018-05-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20180527_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='main_balance',
            field=models.IntegerField(default=0),
        ),
    ]
