# Generated by Django 2.0.5 on 2018-05-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20180519_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='private_key',
            new_name='private_key_hex',
        ),
        migrations.AddField(
            model_name='address',
            name='private_key_wif',
            field=models.TextField(null=True),
        ),
    ]
