# Generated by Django 2.0.5 on 2018-05-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20180527_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='coin',
            field=models.CharField(choices=[('btc', 'btc'), ('eth', 'Ether'), ('beth', 'BETH'), ('bcy', 'bcy'), ('MAN', 'Manna')], max_length=100),
        ),
    ]
