# Generated by Django 2.0.5 on 2018-05-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20180519_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='balance',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=100, null=True),
        ),
    ]
