# Generated by Django 2.0.5 on 2018-05-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_wallet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='coin',
            field=models.CharField(choices=[('(Bitcoin', 'Bitcoin'), ('Ether', 'Ether'), ('bcy', 'bcy')], max_length=100),
        ),
    ]
