# Generated by Django 2.0.5 on 2018-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_auto_20180520_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='network',
            field=models.CharField(default='test', max_length=200, null=True),
        ),
    ]
