# Generated by Django 2.0.5 on 2018-05-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_wallet_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], max_length=200, null=True)),
                ('data', models.TextField()),
            ],
        ),
    ]
