# Generated by Django 2.0.5 on 2018-05-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='coin',
            field=models.CharField(choices=[('(btc', 'btc'), ('Ether', 'Ether'), ('bcy', 'bcy')], max_length=100),
        ),
    ]
