# Generated by Django 2.0.5 on 2018-05-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_auto_20180523_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='coin',
            field=models.CharField(choices=[('btc', 'btc'), ('eth', 'Ether'), ('bcy', 'bcy')], max_length=100),
        ),
    ]
