# Generated by Django 2.0.5 on 2018-05-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20180512_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bit_address',
        ),
    ]
