# Generated by Django 2.0.5 on 2018-05-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_remove_profile_bit_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
